allowBuilds:
  "@parcel/watcher": false
  "@swc/core": false
  "@tailwindcss/oxide": false
  "@tarojs/binding": false
  "@tarojs/cli": false
  core-js: false
  core-js-pure: false
  esbuild: false
  weapp-tailwindcss: false
