// This file is auto-generated by @hey-api/openapi-ts

export const ClassifyInfoSchema = {
  type: "object",
  properties: {
    picture: {
      type: "string",
    },
    name: {
      type: "string",
    },
    id: {
      type: "string",
    },
  },
  required: ["name", "id"],
} as const;

export const WareInfoSchema = {
  type: "object",
  properties: {
    name: {
      type: "string",
    },
    price: {
      type: "number",
    },
    mainPicture: {
      type: "string",
    },
    pictureList: {
      type: "array",
      items: {
        type: "string",
      },
    },
    sales: {
      type: "number",
      title: "销量",
    },
    deac: {
      type: "string",
      title: "描述",
    },
    inventory: {
      type: "number",
      title: "库存",
    },
    id: {
      type: "string",
    },
    liked: {
      type: "boolean",
    },
    wareType: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "string",
        },
      ],
    },
  },
  required: [
    "name",
    "price",
    "mainPicture",
    "pictureList",
    "sales",
    "deac",
    "inventory",
    "id",
    "liked",
    "wareType",
  ],
} as const;
