// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  GetWxRedirectByAppIdGreetData,
  GetWxRedirectByAppIdGreetResponses,
  GetWxRedirectByAppIdGreetErrors,
  GetWxShopCateListData,
  GetWxShopCateListResponses,
  GetWxShopCateProductData,
  GetWxShopCateProductResponses,
  GetWxShopProductSearchData,
  GetWxShopProductSearchResponses,
  GetWxShopProductDetailData,
  GetWxShopProductDetailResponses,
  PostWxShopCartAddData,
  PostWxShopCartAddResponses,
  GetWxShopCartLoadData,
  GetWxShopCartLoadResponses,
  GetWxShopCartDeleteData,
  GetWxShopCartDeleteResponses,
  PostWxShopOrderCreateData,
  PostWxShopOrderCreateResponses,
  PostWxShopOrderPayData,
  PostWxShopOrderPayResponses,
  PostWxShopCartUpdateData,
  PostWxShopCartUpdateResponses,
  GetWxShopAddrListData,
  GetWxShopAddrListResponses,
  PostWxShopAddrAddData,
  PostWxShopAddrAddResponses,
  PostWxShopAddrEditData,
  PostWxShopAddrEditResponses,
  GetWxShopAddrDelData,
  GetWxShopAddrDelResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * 微信用户校验
 */
export const getWxRedirectByAppIdGreet = <ThrowOnError extends boolean = false>(
  options: Options<GetWxRedirectByAppIdGreetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetWxRedirectByAppIdGreetResponses,
    GetWxRedirectByAppIdGreetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/redirect/{appId}/greet",
    ...options,
  });
};

/**
 * 一二级分类列表
 */
export const getWxShopCateList = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopCateListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopCateListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/cate/list",
    ...options,
  });
};

/**
 * 获取二级分类下的产品
 */
export const getWxShopCateProduct = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopCateProductData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopCateProductResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/cate/product",
    ...options,
  });
};

/**
 * 搜索产品（产品名搜索）
 */
export const getWxShopProductSearch = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopProductSearchData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopProductSearchResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/product/search",
    ...options,
  });
};

/**
 * 获取产品详情
 */
export const getWxShopProductDetail = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopProductDetailData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopProductDetailResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/product/detail",
    ...options,
  });
};

/**
 * 加入购物车
 */
export const postWxShopCartAdd = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopCartAddData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopCartAddResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/cart/add",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 获取购物车信息
 */
export const getWxShopCartLoad = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopCartLoadData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopCartLoadResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/cart/load",
    ...options,
  });
};

/**
 * 删除购物车商品
 */
export const getWxShopCartDelete = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopCartDeleteData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopCartDeleteResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/cart/delete",
    ...options,
  });
};

/**
 * 生成订单
 */
export const postWxShopOrderCreate = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopOrderCreateData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopOrderCreateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 支付订单（未完成）
 */
export const postWxShopOrderPay = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopOrderPayData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopOrderPayResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/pay",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 更新购物车商品的数量
 */
export const postWxShopCartUpdate = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopCartUpdateData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopCartUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/cart/update",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 我的地址列表
 */
export const getWxShopAddrList = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopAddrListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopAddrListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/list",
    ...options,
  });
};

/**
 * 新增地址
 */
export const postWxShopAddrAdd = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopAddrAddData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopAddrAddResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/add",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 更新地址
 */
export const postWxShopAddrEdit = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopAddrEditData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopAddrEditResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/edit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 删除地址
 */
export const getWxShopAddrDel = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopAddrDelData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopAddrDelResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/del",
    ...options,
  });
};
