// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  GetWxRedirectByAppIdGreetData,
  GetWxRedirectByAppIdGreetResponses,
  GetWxRedirectByAppIdGreetErrors,
  GetWxRedirectQueryDictData,
  GetWxRedirectQueryDictResponses,
  GetWxRedirectQueryConfigData,
  GetWxRedirectQueryConfigResponses,
  GetWxShopCateListData,
  GetWxShopCateListResponses,
  GetWxShopCateProductData,
  GetWxShopCateProductResponses,
  GetWxShopCateProductErrors,
  GetWxShopProductSearchData,
  GetWxShopProductSearchResponses,
  GetWxShopProductSearchErrors,
  GetWxShopProductDetailData,
  GetWxShopProductDetailResponses,
  PostWxShopOrderPayData,
  PostWxShopOrderPayResponses,
  GetWxShopAddrListData,
  GetWxShopAddrListResponses,
  PostWxShopAddrAddData,
  PostWxShopAddrAddResponses,
  PostWxShopAddrEditData,
  PostWxShopAddrEditResponses,
  GetWxShopAddrDelData,
  GetWxShopAddrDelResponses,
  GetWxShopOrderMyData,
  GetWxShopOrderMyResponses,
  GetWxShopOrderDetailData,
  GetWxShopOrderDetailResponses,
  GetWxShopOrderStatusCountData,
  GetWxShopOrderStatusCountResponses,
  GetWxShopOrderStatusCountErrors,
  PostWxShopAddrViewByIdData,
  PostWxShopAddrViewByIdResponses,
  GetWxShopOrderAddrChangeData,
  GetWxShopOrderAddrChangeResponses,
  GetWxShopOrderCancelData,
  GetWxShopOrderCancelResponses,
  GetWxShopOrderPay2Data,
  GetWxShopOrderPay2Responses,
  GetWxShopBannerListData,
  GetWxShopBannerListResponses,
  GetWxShopBannerListErrors,
  GetWxShopMyServiceOrderData,
  GetWxShopMyServiceOrderResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * 微信用户校验
 */
export const getWxRedirectByAppIdGreet = <ThrowOnError extends boolean = false>(
  options: Options<GetWxRedirectByAppIdGreetData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetWxRedirectByAppIdGreetResponses,
    GetWxRedirectByAppIdGreetErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/redirect/{appId}/greet",
    ...options,
  });
};

/**
 * 获取字典
 */
export const getWxRedirectQueryDict = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxRedirectQueryDictData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxRedirectQueryDictResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/redirect/queryDict",
    ...options,
  });
};

/**
 * 获取系统参数
 * 只能获取非系统内置的参数
 */
export const getWxRedirectQueryConfig = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxRedirectQueryConfigData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxRedirectQueryConfigResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/redirect/queryConfig",
    ...options,
  });
};

/**
 * 一二级分类列表
 */
export const getWxShopCateList = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopCateListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopCateListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/cate/list",
    ...options,
  });
};

/**
 * 获取二级分类下的产品
 */
export const getWxShopCateProduct = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopCateProductData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopCateProductResponses,
    GetWxShopCateProductErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/cate/product",
    ...options,
  });
};

/**
 * 搜索产品（产品名搜索）
 */
export const getWxShopProductSearch = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopProductSearchData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopProductSearchResponses,
    GetWxShopProductSearchErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/product/search",
    ...options,
  });
};

/**
 * 获取产品详情
 */
export const getWxShopProductDetail = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopProductDetailData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopProductDetailResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/product/detail",
    ...options,
  });
};

/**
 * 立即购买
 */
export const postWxShopOrderPay = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopOrderPayData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopOrderPayResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/pay",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 我的地址列表
 */
export const getWxShopAddrList = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopAddrListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopAddrListResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/list",
    ...options,
  });
};

/**
 * 新增地址
 */
export const postWxShopAddrAdd = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopAddrAddData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopAddrAddResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/add",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 更新地址
 */
export const postWxShopAddrEdit = <ThrowOnError extends boolean = false>(
  options?: Options<PostWxShopAddrEditData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    PostWxShopAddrEditResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/edit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * 删除地址
 */
export const getWxShopAddrDel = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopAddrDelData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopAddrDelResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/del",
    ...options,
  });
};

/**
 * 我的订单
 * 查全部订单， status参数 不传，
 */
export const getWxShopOrderMy = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopOrderMyData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopOrderMyResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/my",
    ...options,
  });
};

/**
 * 订单详情
 */
export const getWxShopOrderDetail = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopOrderDetailData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopOrderDetailResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/detail",
    ...options,
  });
};

/**
 * 各个状态的订单数量
 */
export const getWxShopOrderStatusCount = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopOrderStatusCountData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopOrderStatusCountResponses,
    GetWxShopOrderStatusCountErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/status/count",
    ...options,
  });
};

/**
 * 根据id获取地址详情
 */
export const postWxShopAddrViewById = <ThrowOnError extends boolean = false>(
  options: Options<PostWxShopAddrViewByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostWxShopAddrViewByIdResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/addr/view/{id}",
    ...options,
  });
};

/**
 * 修改订单地址
 */
export const getWxShopOrderAddrChange = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopOrderAddrChangeData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopOrderAddrChangeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/addr/change",
    ...options,
  });
};

/**
 * 取消订单
 */
export const getWxShopOrderCancel = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopOrderCancelData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopOrderCancelResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/cancel",
    ...options,
  });
};

/**
 * 订单页面付款接口
 */
export const getWxShopOrderPay2 = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopOrderPay2Data, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopOrderPay2Responses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/order/pay2",
    ...options,
  });
};

/**
 * 获取机构的banner列表
 */
export const getWxShopBannerList = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopBannerListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopBannerListResponses,
    GetWxShopBannerListErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/banner/list",
    ...options,
  });
};

/**
 * 我的服务类订单
 * 服务类订单，返回所有订单的服务。
 */
export const getWxShopMyServiceOrder = <ThrowOnError extends boolean = false>(
  options?: Options<GetWxShopMyServiceOrderData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWxShopMyServiceOrderResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/wx/shop/my/service/order",
    ...options,
  });
};
