// This file is auto-generated by @hey-api/openapi-ts

export type CartItem = {
  createdAt: string;
  id: number;
  isService: number;
  itemId: number;
  itemName: string;
  orderNo: string;
  orgId: string;
  price: number;
  productId: number;
  productImage: string;
  productName: string;
  qrCode: string;
  qrCodeExpireTime: string;
  qty: number;
  serviceDate: string;
  totalPrice: number;
  usedQty: number;
};

export type SkuListItem = {
  id: number;
  image: string;
  orgId: string;
  originalPrice: number;
  price: number;
  productId: number;
  skuCode: string;
  specs: string;
  status: number;
  stock: number;
};

export type ServiceInfo = {
  id: number;
  itemId: number;
  itemName: string;
  num: number;
  price: number;
  productId: number;
  selectedItems: string;
  totalPrice: number;
  updateTime: string;
  qty: number;
  usedQty: number;
};

export type SubCategoryInfo = {
  id: number;
  categoryId: number;
  categoryName: string;
  orgId: string;
  name: string;
  description: string;
  sortOrder: number;
  status: number;
  createdAt: string;
  updatedAt: string;
  logo?: string;
};

export type BannerItem = {
  productId?: string;
  imagePath: string;
  name: string;
  orgId: string;
  updatedAt: string;
  bannerOrder: number;
  bannerType: string;
  createdAt: string;
  id: string;
};

export type OrderDetail = {
  id: number;
  orderNo: string;
  orgId: string;
  userId: string;
  addressId: number;
  totalAmount: number;
  paymentAmount: number;
  freightAmount: number;
  discountAmount: number;
  paymentType: unknown;
  paymentTime: unknown;
  status: number;
  deliveryCompany: unknown;
  deliveryNo: unknown;
  deliveryTime: unknown;
  receiveTime: unknown;
  createdAt: string;
  updatedAt: string;
  remark: unknown;
  applyPayNo: unknown;
  payId: unknown;
  isService: number;
  itemList: Array<CartItem>;
};

export type OrderListItem = {
  orderNo: string;
  status: number;
  productList: Array<{
    productId: number;
    productImage: string;
    productName: string;
    services: Array<{
      itemId: number;
      itemName: string;
      price: number;
      qrCode: string;
      qty: number;
      serviceDate: string;
      totalPrice: number;
      usedQty: number;
    }>;
  }>;
  paymentAmount: number;
  createAt: string;
  isService: number;
};

export type AddressInfo = {
  id?: number;
  userId?: string;
  receiverName?: string;
  receiverPhone?: string;
  province?: string;
  city?: string;
  district?: string;
  street?: string;
  detailAddress?: string;
  postalCode?: string;
  isDefault?: number;
  tag?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type PayResult = {
  nonce_str: string;
  package: string;
  time_stamp: string;
  pay_option: string;
  mch_order_id: string;
  pay_id: string;
  app_id: string;
  sign_type: string;
  pay_sign: string;
  status: string;
};

export type ProductInfo = {
  id: number;
  orgId: string;
  subCategoryId: number;
  subCategoryName: string;
  name: string;
  description: string;
  type: string;
  price: number;
  originalPrice: number;
  mainImage: string;
  productTags: string;
  serviceTags: string;
  detailImages: string;
  detailContent: string;
  status: number;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
  itemsList?: Array<ServiceInfo>;
  skuList?: Array<SkuListItem>;
};

export type CateInfo = {
  id: number;
  name: string;
  orgId: string;
  description: string;
  sortOrder: number;
  status: number;
  subCategoryList: Array<SubCategoryInfo>;
  logo?: string;
};

export type DictItem = {
  createBy: string;
  createTime: string;
  updateTime: unknown;
  updateBy: unknown;
  remark: unknown;
  dictCode: number;
  dictSort: number;
  dictLabel: string;
  dictValue: string;
  dictType: string;
  cssClass: unknown;
  listClass: unknown;
  isDefault: string;
  status: string;
  default: boolean;
};

export type GetWxRedirectByAppIdGreetData = {
  body?: never;
  path: {
    appId: string;
  };
  query?: {
    code?: string;
    state?: string;
    orgId?: string;
  };
  url: "/wx/redirect/{appId}/greet";
};

export type GetWxRedirectByAppIdGreetErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type GetWxRedirectByAppIdGreetError =
  GetWxRedirectByAppIdGreetErrors[keyof GetWxRedirectByAppIdGreetErrors];

export type GetWxRedirectByAppIdGreetResponses = {
  200: {
    code: number;
    data: string;
    msg: string;
  };
};

export type GetWxRedirectByAppIdGreetResponse =
  GetWxRedirectByAppIdGreetResponses[keyof GetWxRedirectByAppIdGreetResponses];

export type GetWxRedirectQueryDictData = {
  body?: never;
  path?: never;
  query?: {
    dictType?: string;
  };
  url: "/wx/redirect/queryDict";
};

export type GetWxRedirectQueryDictResponses = {
  200: {
    msg: string;
    code: number;
    data: Array<DictItem>;
  };
};

export type GetWxRedirectQueryDictResponse =
  GetWxRedirectQueryDictResponses[keyof GetWxRedirectQueryDictResponses];

export type GetWxRedirectQueryConfigData = {
  body?: never;
  path?: never;
  query?: {
    key?: string;
  };
  url: "/wx/redirect/queryConfig";
};

export type GetWxRedirectQueryConfigResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type GetWxRedirectQueryConfigResponse =
  GetWxRedirectQueryConfigResponses[keyof GetWxRedirectQueryConfigResponses];

export type GetWxOrgInfoByOrgIdData = {
  body?: never;
  path: {
    orgId: string;
  };
  query?: never;
  url: "/wx/orgInfo/{orgId}";
};

export type GetWxOrgInfoByOrgIdResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type GetWxOrgInfoByOrgIdResponse =
  GetWxOrgInfoByOrgIdResponses[keyof GetWxOrgInfoByOrgIdResponses];

export type GetWxShopCateListData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
  };
  url: "/wx/shop/cate/list";
};

export type GetWxShopCateListResponses = {
  200: {
    msg: string;
    code: number;
    data: Array<CateInfo>;
  };
};

export type GetWxShopCateListResponse =
  GetWxShopCateListResponses[keyof GetWxShopCateListResponses];

export type GetWxShopCateProductData = {
  body?: never;
  path?: never;
  query?: {
    subCategoryId?: string;
    pageSize?: string;
    pageNum?: string;
    orderBy?: string;
  };
  url: "/wx/shop/cate/product";
};

export type GetWxShopCateProductErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type GetWxShopCateProductError =
  GetWxShopCateProductErrors[keyof GetWxShopCateProductErrors];

export type GetWxShopCateProductResponses = {
  200: {
    total: number;
    rows: Array<ProductInfo>;
    code: number;
    msg: unknown;
  };
};

export type GetWxShopCateProductResponse =
  GetWxShopCateProductResponses[keyof GetWxShopCateProductResponses];

export type GetWxShopProductSearchData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
    searchKey?: string;
    pageNum?: string;
    pageSize?: string;
  };
  url: "/wx/shop/product/search";
};

export type GetWxShopProductSearchErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type GetWxShopProductSearchError =
  GetWxShopProductSearchErrors[keyof GetWxShopProductSearchErrors];

export type GetWxShopProductSearchResponses = {
  200: {
    total: number;
    rows: Array<ProductInfo>;
    code: number;
    msg?: unknown;
  };
};

export type GetWxShopProductSearchResponse =
  GetWxShopProductSearchResponses[keyof GetWxShopProductSearchResponses];

export type GetWxShopProductDetailData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
    productId?: string;
  };
  url: "/wx/shop/product/detail";
};

export type GetWxShopProductDetailResponses = {
  200: {
    msg: string;
    code: number;
    data: ProductInfo;
  };
};

export type GetWxShopProductDetailResponse =
  GetWxShopProductDetailResponses[keyof GetWxShopProductDetailResponses];

export type PostWxShopOrderPayData = {
  body?: {
    /**
     * 地址id
     * 服务型商品可以不传
     */
    addressId: number;
    /**
     * 支付方式
     * 支付方式：1-支付宝，2-微信，3-银行卡
     */
    payType: number;
    /**
     * 订单总金额
     */
    totalAmount: number;
    /**
     * 实付金额
     */
    paymentAmount: number;
    /**
     * 运费
     */
    freightAmount: number;
    /**
     * 优惠金额
     */
    discountAmount: number;
    /**
     * 机构id
     */
    orgId: string;
    /**
     * 商品列表
     */
    productList: Array<{
      /**
       * 商品id
       */
      productId: number;
      /**
       * 商品名称
       */
      productName: string;
      /**
       * 规格列表
       */
      skuList?: Array<{
        /**
         * 规格id
         */
        itemId?: number;
        /**
         * 规格名称
         */
        itemName?: string;
        /**
         * 价格
         */
        price?: number;
        /**
         * 数量
         */
        num?: number;
      }>;
    }>;
  };
  path?: never;
  query?: never;
  url: "/wx/shop/order/pay";
};

export type PostWxShopOrderPayResponses = {
  200: {
    msg: string;
    code: number;
    data: PayResult;
  };
};

export type PostWxShopOrderPayResponse =
  PostWxShopOrderPayResponses[keyof PostWxShopOrderPayResponses];

export type GetWxShopAddrListData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
  };
  url: "/wx/shop/addr/list";
};

export type GetWxShopAddrListResponses = {
  200: {
    msg: string;
    code: number;
    data: Array<AddressInfo>;
  };
};

export type GetWxShopAddrListResponse =
  GetWxShopAddrListResponses[keyof GetWxShopAddrListResponses];

export type PostWxShopAddrAddData = {
  body?: {
    receiverName: string;
    receiverPhone: string;
    province: string;
    city: string;
    district: string;
    street: string;
    detailAddress: string;
    postalCode: string;
    isDefault: number;
    tag: string;
  };
  path?: never;
  query?: never;
  url: "/wx/shop/addr/add";
};

export type PostWxShopAddrAddResponses = {
  200: {
    msg: string;
    code: number;
  };
};

export type PostWxShopAddrAddResponse =
  PostWxShopAddrAddResponses[keyof PostWxShopAddrAddResponses];

export type PostWxShopAddrEditData = {
  body?: AddressInfo;
  path?: never;
  query?: never;
  url: "/wx/shop/addr/edit";
};

export type PostWxShopAddrEditResponses = {
  200: {
    msg: string;
    code: number;
  };
};

export type PostWxShopAddrEditResponse =
  PostWxShopAddrEditResponses[keyof PostWxShopAddrEditResponses];

export type GetWxShopAddrDelData = {
  body?: never;
  path?: never;
  query?: {
    id?: string;
  };
  url: "/wx/shop/addr/del";
};

export type GetWxShopAddrDelResponses = {
  200: {
    msg: string;
    code: number;
  };
};

export type GetWxShopAddrDelResponse =
  GetWxShopAddrDelResponses[keyof GetWxShopAddrDelResponses];

export type GetWxShopOrderMyData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
    /**
     * 非必填，不传查全部
     */
    status?: string;
    pageSize?: string;
    pageNum?: string;
  };
  url: "/wx/shop/order/my";
};

export type GetWxShopOrderMyResponses = {
  200: {
    total: number;
    rows: Array<OrderListItem>;
    code: number;
    msg: unknown;
  };
};

export type GetWxShopOrderMyResponse =
  GetWxShopOrderMyResponses[keyof GetWxShopOrderMyResponses];

export type GetWxShopOrderDetailData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
    orderNo?: string;
  };
  url: "/wx/shop/order/detail";
};

export type GetWxShopOrderDetailResponses = {
  200: {
    msg: string;
    code: number;
    data: {
      order: OrderDetail;
    };
  };
};

export type GetWxShopOrderDetailResponse =
  GetWxShopOrderDetailResponses[keyof GetWxShopOrderDetailResponses];

export type GetWxShopOrderStatusCountData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
  };
  url: "/wx/shop/order/status/count";
};

export type GetWxShopOrderStatusCountErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type GetWxShopOrderStatusCountError =
  GetWxShopOrderStatusCountErrors[keyof GetWxShopOrderStatusCountErrors];

export type GetWxShopOrderStatusCountResponses = {
  200: {
    code: number;
    msg: string;
    data?: string;
  };
};

export type GetWxShopOrderStatusCountResponse =
  GetWxShopOrderStatusCountResponses[keyof GetWxShopOrderStatusCountResponses];

export type PostWxShopAddrViewByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    orgId?: string;
  };
  url: "/wx/shop/addr/view/{id}";
};

export type PostWxShopAddrViewByIdResponses = {
  200: {
    msg: string;
    code: number;
    data: AddressInfo;
  };
};

export type PostWxShopAddrViewByIdResponse =
  PostWxShopAddrViewByIdResponses[keyof PostWxShopAddrViewByIdResponses];

export type GetWxShopOrderAddrChangeData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
    /**
     * 地址的id
     */
    addId?: number;
    /**
     * 订单编号
     */
    orderNo?: string;
  };
  url: "/wx/shop/order/addr/change";
};

export type GetWxShopOrderAddrChangeResponses = {
  200: {
    msg: string;
    code: number;
    data: Array<AddressInfo>;
  };
};

export type GetWxShopOrderAddrChangeResponse =
  GetWxShopOrderAddrChangeResponses[keyof GetWxShopOrderAddrChangeResponses];

export type GetWxShopOrderCancelData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
    /**
     * 订单编号
     */
    orderNo?: string;
  };
  url: "/wx/shop/order/cancel";
};

export type GetWxShopOrderCancelResponses = {
  200: {
    msg: string;
    code: number;
  };
};

export type GetWxShopOrderCancelResponse =
  GetWxShopOrderCancelResponses[keyof GetWxShopOrderCancelResponses];

export type GetWxShopOrderPay2Data = {
  body?: never;
  path?: never;
  query?: {
    orderNo?: string;
  };
  url: "/wx/shop/order/pay2";
};

export type GetWxShopOrderPay2Responses = {
  200: {
    msg: string;
    code: number;
    data: PayResult;
  };
};

export type GetWxShopOrderPay2Response =
  GetWxShopOrderPay2Responses[keyof GetWxShopOrderPay2Responses];

export type GetWxShopBannerListData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
  };
  url: "/wx/shop/banner/list";
};

export type GetWxShopBannerListErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type GetWxShopBannerListError =
  GetWxShopBannerListErrors[keyof GetWxShopBannerListErrors];

export type GetWxShopBannerListResponses = {
  200: {
    code: number;
    msg: string;
    data?: Array<BannerItem>;
  };
};

export type GetWxShopBannerListResponse =
  GetWxShopBannerListResponses[keyof GetWxShopBannerListResponses];

export type GetWxShopMyServiceOrderData = {
  body?: never;
  path?: never;
  query?: {
    pageSize?: string;
    pageNum?: string;
    /**
     * 不传：全部,  2:未核销完的服务，3：已经核销完的。
     */
    status?: number;
  };
  url: "/wx/shop/my/service/order";
};

export type GetWxShopMyServiceOrderResponses = {
  200: {
    total: number;
    rows: Array<OrderListItem>;
    code: number;
    msg: unknown;
  };
};

export type GetWxShopMyServiceOrderResponse =
  GetWxShopMyServiceOrderResponses[keyof GetWxShopMyServiceOrderResponses];

export type PostWxShopAfterSaleApplyData = {
  body?: {
    /**
     * 订单id
     */
    orderNo: string;
    /**
     * 申请退款金额
     */
    applyAmount: number;
  };
  path?: never;
  query?: never;
  url: "/wx/shop/after/sale/apply";
};

export type PostWxShopAfterSaleApplyErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type PostWxShopAfterSaleApplyError =
  PostWxShopAfterSaleApplyErrors[keyof PostWxShopAfterSaleApplyErrors];

export type PostWxShopAfterSaleApplyResponses = {
  200: {
    code: number;
    msg: string;
    data?: string;
  };
};

export type PostWxShopAfterSaleApplyResponse =
  PostWxShopAfterSaleApplyResponses[keyof PostWxShopAfterSaleApplyResponses];

export type GetWxShopAfterSaleListData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * 按接口说明传状态。不传查全部
     */
    status?: string;
    pageSize?: number;
    pageNum?: number;
  };
  url: "/wx/shop/after/sale/list";
};

export type GetWxShopAfterSaleListResponses = {
  200: {
    total: number;
    rows: Array<string>;
    code: number;
    msg: unknown;
  };
};

export type GetWxShopAfterSaleListResponse =
  GetWxShopAfterSaleListResponses[keyof GetWxShopAfterSaleListResponses];

export type ClientOptions = {
  baseURL: string;
};
