// This file is auto-generated by @hey-api/openapi-ts

export type SkuInfo = {
  id: number;
  productId: number;
  orgId: string;
  skuCode: string;
  specs: string;
  price: number;
  originalPrice: number;
  stock: number;
  image: string;
  status: number;
};

export type SubCategoryInfo = {
  id: number;
  categoryId: number;
  categoryName: string;
  orgId: string;
  name: string;
  description: string;
  sortOrder: number;
  status: number;
  createdAt: string;
  updatedAt: string;
};

export type AddressInfo = {
  id?: number;
  userId?: string;
  receiverName?: string;
  receiverPhone?: string;
  province?: string;
  city?: string;
  district?: string;
  street?: string;
  detailAddress?: string;
  postalCode?: string;
  isDefault?: number;
  tag?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type CartItem = {
  id?: number;
  cartId?: number;
  orgId?: string;
  productId?: number;
  productName?: string;
  skuId?: number;
  skuName?: string;
  quantity?: number;
  price?: number;
  isService?: number;
  serviceDate?: unknown;
  qrCodeStatus?: number;
  selected?: number;
  createdAt?: string;
  updatedAt?: string;
};

export type CartInfo = {
  id: number;
  userId: string;
  orgId: string;
  sessionId: unknown;
  createdAt: string;
  updatedAt: string;
  itemList: Array<CartItem>;
};

export type ProductInfo = {
  id: number;
  orgId: string;
  subCategoryId: number;
  subCategoryName: string;
  name: string;
  description: string;
  type: string;
  price: number;
  originalPrice: number;
  mainImage: string;
  productTags: string;
  serviceTags: string;
  detailImages: string;
  detailContent: string;
  status: number;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
  skuList: Array<SkuInfo>;
};

export type CateInfo = {
  id: number;
  name: string;
  orgId: string;
  description: string;
  sortOrder: number;
  status: number;
  subCategoryList: Array<SubCategoryInfo>;
};

export type GetWxRedirectByAppIdGreetData = {
  body?: never;
  path: {
    appId: string;
  };
  query?: {
    code?: string;
    state?: string;
    orgId?: string;
  };
  url: "/wx/redirect/{appId}/greet";
};

export type GetWxRedirectByAppIdGreetErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type GetWxRedirectByAppIdGreetError =
  GetWxRedirectByAppIdGreetErrors[keyof GetWxRedirectByAppIdGreetErrors];

export type GetWxRedirectByAppIdGreetResponses = {
  200: {
    code: number;
    data: string;
    msg: string;
  };
};

export type GetWxRedirectByAppIdGreetResponse =
  GetWxRedirectByAppIdGreetResponses[keyof GetWxRedirectByAppIdGreetResponses];

export type GetWxShopCateListData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
  };
  url: "/wx/shop/cate/list";
};

export type GetWxShopCateListResponses = {
  200: {
    msg: string;
    code: number;
    data: Array<CateInfo>;
  };
};

export type GetWxShopCateListResponse =
  GetWxShopCateListResponses[keyof GetWxShopCateListResponses];

export type GetWxShopCateProductData = {
  body?: never;
  path?: never;
  query?: {
    subCategoryId?: string;
  };
  url: "/wx/shop/cate/product";
};

export type GetWxShopCateProductResponses = {
  200: {
    total: number;
    rows: Array<ProductInfo>;
    code: number;
    msg: unknown;
  };
};

export type GetWxShopCateProductResponse =
  GetWxShopCateProductResponses[keyof GetWxShopCateProductResponses];

export type GetWxShopProductSearchData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
    searchKey?: string;
  };
  url: "/wx/shop/product/search";
};

export type GetWxShopProductSearchResponses = {
  200: {
    total: number;
    rows: Array<ProductInfo>;
    code: number;
    msg?: unknown;
  };
};

export type GetWxShopProductSearchResponse =
  GetWxShopProductSearchResponses[keyof GetWxShopProductSearchResponses];

export type GetWxShopProductDetailData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
    productId?: string;
  };
  url: "/wx/shop/product/detail";
};

export type GetWxShopProductDetailResponses = {
  200: {
    msg: string;
    code: number;
    data: ProductInfo;
  };
};

export type GetWxShopProductDetailResponse =
  GetWxShopProductDetailResponses[keyof GetWxShopProductDetailResponses];

export type PostWxShopCartAddData = {
  body?: {
    cartId: number;
    orgId: string;
    productId: number;
    quantity: number;
    skuId: number;
    productName: string;
    skuName: string;
  };
  path?: never;
  query?: never;
  url: "/wx/shop/cart/add";
};

export type PostWxShopCartAddResponses = {
  200: {
    msg: string;
    code: number;
  };
};

export type PostWxShopCartAddResponse =
  PostWxShopCartAddResponses[keyof PostWxShopCartAddResponses];

export type GetWxShopCartLoadData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
  };
  url: "/wx/shop/cart/load";
};

export type GetWxShopCartLoadResponses = {
  200: {
    msg: string;
    code: number;
    data: CartInfo;
  };
};

export type GetWxShopCartLoadResponse =
  GetWxShopCartLoadResponses[keyof GetWxShopCartLoadResponses];

export type GetWxShopCartDeleteData = {
  body?: never;
  path?: never;
  query?: {
    cartItemId?: string;
  };
  url: "/wx/shop/cart/delete";
};

export type GetWxShopCartDeleteResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type GetWxShopCartDeleteResponse =
  GetWxShopCartDeleteResponses[keyof GetWxShopCartDeleteResponses];

export type PostWxShopOrderCreateData = {
  body?: {
    addressId: number;
    orgId: string;
    totalAmount: number;
    paymentAmount: number;
    freightAmount: number;
    discountAmount: number;
    itemList: Array<CartItem>;
  };
  path?: never;
  query?: never;
  url: "/wx/shop/order/create";
};

export type PostWxShopOrderCreateErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type PostWxShopOrderCreateError =
  PostWxShopOrderCreateErrors[keyof PostWxShopOrderCreateErrors];

export type PostWxShopOrderCreateResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type PostWxShopOrderCreateResponse =
  PostWxShopOrderCreateResponses[keyof PostWxShopOrderCreateResponses];

export type PostWxShopOrderPayData = {
  body?: {
    orderNo: string;
  };
  path?: never;
  query?: never;
  url: "/wx/shop/order/pay";
};

export type PostWxShopOrderPayErrors = {
  400: {
    code: number;
    msg: string;
  };
};

export type PostWxShopOrderPayError =
  PostWxShopOrderPayErrors[keyof PostWxShopOrderPayErrors];

export type PostWxShopOrderPayResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type PostWxShopOrderPayResponse =
  PostWxShopOrderPayResponses[keyof PostWxShopOrderPayResponses];

export type PostWxShopCartUpdateData = {
  body?: {
    id: number;
    quantity: number;
  };
  path?: never;
  query?: never;
  url: "/wx/shop/cart/update";
};

export type PostWxShopCartUpdateResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type PostWxShopCartUpdateResponse =
  PostWxShopCartUpdateResponses[keyof PostWxShopCartUpdateResponses];

export type GetWxShopAddrListData = {
  body?: never;
  path?: never;
  query?: {
    orgId?: string;
  };
  url: "/wx/shop/addr/list";
};

export type GetWxShopAddrListResponses = {
  200: {
    msg: string;
    code: number;
    data: Array<AddressInfo>;
  };
};

export type GetWxShopAddrListResponse =
  GetWxShopAddrListResponses[keyof GetWxShopAddrListResponses];

export type PostWxShopAddrAddData = {
  body?: {
    receiverName: string;
    receiverPhone: string;
    province: string;
    city: string;
    district: string;
    street: string;
    detailAddress: string;
    postalCode: string;
    isDefault: number;
    tag: string;
  };
  path?: never;
  query?: never;
  url: "/wx/shop/addr/add";
};

export type PostWxShopAddrAddResponses = {
  200: {
    msg: string;
    code: number;
  };
};

export type PostWxShopAddrAddResponse =
  PostWxShopAddrAddResponses[keyof PostWxShopAddrAddResponses];

export type PostWxShopAddrEditData = {
  body?: AddressInfo;
  path?: never;
  query?: never;
  url: "/wx/shop/addr/edit";
};

export type PostWxShopAddrEditResponses = {
  200: {
    msg: string;
    code: number;
  };
};

export type PostWxShopAddrEditResponse =
  PostWxShopAddrEditResponses[keyof PostWxShopAddrEditResponses];

export type GetWxShopAddrDelData = {
  body?: never;
  path?: never;
  query?: {
    id?: string;
  };
  url: "/wx/shop/addr/del";
};

export type GetWxShopAddrDelResponses = {
  200: {
    msg: string;
    code: number;
  };
};

export type GetWxShopAddrDelResponse =
  GetWxShopAddrDelResponses[keyof GetWxShopAddrDelResponses];

export type ClientOptions = {
  baseURL: string;
};
